### ISSUE TITLE
Something like a key is missing?

### ISSUE THREAD

**Issue by Bluepeltz** [JoeSiu/discord-chatbot#1]
![image](https://github.com/JoeSiu/discord-chatbot/assets/102773304/0fdc35d6-2f9d-4d2d-9299-2b351f2e60f0)

**Comment by JoeSiu** [comment]
@Bluepeltz it's due to the old poe api version being used, I have updated it to the latest version (v0.4.7). run a ```git pull```, then ```pip install -r requirements.txt``` should fix the issue
