### ISSUE TITLE
KeyError: 'chatOfBotDisplayName' Error 500

### ISSUE THREAD

**Issue by Bluepeltz** [JoeSiu/discord-chatbot#5]
It was working all fine till I changed it's nickname in a server and display name, I changed it to something else again, and it still does that.

**Comment by Bluepeltz** [comment]
Also "  raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.
[2023-07-03 09:01:01] [ERROR   ] discord: Fail to create bot 'poe' on start, exiting..."

**Comment by JoeSiu** [comment]
@Bluepeltz this looks like an error from poe API, make sure your poe account is still active. Also, making too many requests to poe.com can cause this error. You can try use another poe account to see if it is still working

**Comment by JoeSiu** [comment]
Seems like it's an issue with the poe api library, need to wait for the original author to fix then

https://github.com/ading2210/poe-api/issues/141

**Comment by Bluepeltz** [comment]
![image](https://github.com/JoeSiu/discord-chatbot/assets/102773304/0e615483-3230-44cb-a79a-076831c9d9eb)

What does this mean?

**Comment by JoeSiu** [comment]
I am not sure what that mean also unfortunately, haven't look deep into the API itself :(

**Comment by BandarAA** [comment]
> ![image](https://user-images.githubusercontent.com/102773304/250612937-0e615483-3230-44cb-a79a-076831c9d9eb.png)
> 
> What does this mean?

In the poe.py file, search for chatOfBotDisplayName. You'll find two instances of this string under the get_bot function. Change them into "chatOfBotHandle" and it will work again. Please note that you don't have to change the session key.

**Comment by JoeSiu** [comment]
Updated poe API, run a ```git pull``` + ```pip install -r requirements.txt``` and see
